#ifndef LILY_EXTEND_BINDINGS_H
#define LILY_EXTEND_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_EXTEND_EXPORT __declspec(dllexport)
#else
#define LILY_EXTEND_EXPORT
#endif

LILY_EXTEND_EXPORT
const char *lily_extend_info_table[] = {
    "\0\0"
    ,"F\0render_string\0(String,String): Result[String,Boolean]"
    ,"F\0parse_string\0(String,String): Result[String,Boolean]"
    ,"F\0parse_expr\0(String,String): Result[String,String]"
    ,"F\0parse_rewind\0(String,String,String): String"
    ,"Z"
};
#define LILY_DECLARE_EXTEND_CALL_TABLE \
LILY_EXTEND_EXPORT \
lily_call_entry_func lily_extend_call_table[] = { \
    NULL, \
    lily_extend__render_string, \
    lily_extend__parse_string, \
    lily_extend__parse_expr, \
    lily_extend__parse_rewind, \
};
#endif
