CC=gcc
CFLAGS=-c -g3 -Wall

BINDIR=bin
OBJDIR=objdir

# todo: Look into making this autogenerated, instead of pretending that the deps
#       are correct.
CORE_OBJECTS=$(OBJDIR)/lily_parser.o \
			$(OBJDIR)/lily_lexer.o \
			$(OBJDIR)/lily_ast.o \
			$(OBJDIR)/lily_emitter.o \
			$(OBJDIR)/lily_symtab.o \
			$(OBJDIR)/lily_vm.o \
			$(OBJDIR)/lily_interp.o \
			$(OBJDIR)/lily_debug.o \
			$(OBJDIR)/lily_error.o \
			$(OBJDIR)/lily_msgbuf.o \
			$(OBJDIR)/lily_pkg_str.o

FS_OBJECTS=$(CORE_OBJECTS) \
			$(OBJDIR)/fs_main.o

STRLOAD_OBJECTS=$(CORE_OBJECTS) \
				$(OBJDIR)/strload_main.o

all: lily_fs lily_strload

clean:
	rm -f $(OBJDIR)/* lily_fs lily_strload

lily_strload: $(STRLOAD_OBJECTS)
	$(CC) $(STRLOAD_OBJECTS) -o lily_strload

lily_fs: $(FS_OBJECTS)
	$(CC) $(FS_OBJECTS) -o lily_fs

# Becomes an executable
$(OBJDIR)/fs_main.o: fs_main.c lily_lexer.h lily_parser.h lily_emitter.h \
					 lily_symtab.h
	$(CC) $(CFLAGS) fs_main.c -o $(OBJDIR)/fs_main.o

$(OBJDIR)/strload_main.o: strload_main.c lily_interp.h
	$(CC) $(CFLAGS) strload_main.c -o $(OBJDIR)/strload_main.o

# Core
$(OBJDIR)/lily_lexer.o: lily_lexer.c lily_lexer.h lily_impl.h
	$(CC) $(CFLAGS) lily_lexer.c -o $(OBJDIR)/lily_lexer.o

$(OBJDIR)/lily_parser.o: lily_parser.c lily_lexer.h lily_impl.h lily_symtab.h \
						 lily_ast.h lily_vm.h lily_expr_op.h
	$(CC) $(CFLAGS) lily_parser.c -o $(OBJDIR)/lily_parser.o

$(OBJDIR)/lily_ast.o: lily_ast.c lily_ast.h lily_symtab.h lily_impl.h \
					  lily_expr_op.h
	$(CC) $(CFLAGS) lily_ast.c -o $(OBJDIR)/lily_ast.o

$(OBJDIR)/lily_emitter.o: lily_emitter.c lily_opcode.h lily_impl.h \
						  lily_emit_table.h
	$(CC) $(CFLAGS) lily_emitter.c -o $(OBJDIR)/lily_emitter.o

$(OBJDIR)/lily_symtab.o: lily_symtab.c lily_symtab.h lily_seed_symtab.h
	$(CC) $(CFLAGS) lily_symtab.c -o $(OBJDIR)/lily_symtab.o

$(OBJDIR)/lily_vm.o: lily_vm.c lily_vm.h
	$(CC) $(CFLAGS) lily_vm.c -o $(OBJDIR)/lily_vm.o

$(OBJDIR)/lily_interp.o: lily_interp.c lily_interp.h
	$(CC) $(CFLAGS) lily_interp.c -o $(OBJDIR)/lily_interp.o

$(OBJDIR)/lily_debug.o: lily_debug.c lily_debug.h
	$(CC) $(CFLAGS) lily_debug.c -o $(OBJDIR)/lily_debug.o

$(OBJDIR)/lily_error.o: lily_error.c lily_error.h
	$(CC) $(CFLAGS) lily_error.c -o $(OBJDIR)/lily_error.o

$(OBJDIR)/lily_msgbuf.o: lily_msgbuf.c lily_msgbuf.h
	$(CC) $(CFLAGS) lily_msgbuf.c -o $(OBJDIR)/lily_msgbuf.o

$(OBJDIR)/lily_pkg_str.o: lily_pkg_str.c lily_pkg_str.h
	$(CC) $(CFLAGS) lily_pkg_str.c -o $(OBJDIR)/lily_pkg_str.o

.PHONY: clean all
