#ifndef LILY_PACKAGELIB_BINDINGS_H
#define LILY_PACKAGELIB_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_PACKAGELIB_EXPORT __declspec(dllexport)
#else
#define LILY_PACKAGELIB_EXPORT
#endif

LILY_PACKAGELIB_EXPORT
const char *lily_packagelib_info_table[] = {
    "\0\0"
    ,"F\0make_list\0[A](A): List[A]"
    ,"Z"
};
#define LILY_DECLARE_PACKAGELIB_CALL_TABLE \
LILY_PACKAGELIB_EXPORT \
lily_call_entry_func lily_packagelib_call_table[] = { \
    NULL, \
    lily_packagelib__make_list, \
};
#endif
