#ifndef LILY_WARM_BINDINGS_H
#define LILY_WARM_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_WARM_EXPORT __declspec(dllexport)
#else
#define LILY_WARM_EXPORT
#endif

#define warm_Color_Orange_VALUE 2
#define warm_Color_Red_VALUE 0
#define warm_Color_Yellow_VALUE 1

LILY_WARM_EXPORT
const char *lily_warm_info_table[] = {
    "\1Color\0"
    ,"E\3Color\0< Integer"
    ,"V\0Orange\0=2"
    ,"V\0Red\0=0"
    ,"V\0Yellow\0=1"
    ,"Z"
};
#define LILY_DECLARE_WARM_CALL_TABLE \
LILY_WARM_EXPORT \
lily_call_entry_func lily_warm_call_table[] = { \
    NULL, \
    NULL, \
    NULL, \
    NULL, \
    NULL, \
};
#endif
