#ifndef LILY_FARM_BINDINGS_H
#define LILY_FARM_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_FARM_EXPORT __declspec(dllexport)
#else
#define LILY_FARM_EXPORT
#endif

LILY_FARM_EXPORT
const char *lily_farm_info_table[] = {
    "\0\0"
    ,"R\0carrot_count\0Integer"
    ,"Z"
};
#define LILY_DECLARE_FARM_CALL_TABLE \
LILY_FARM_EXPORT \
lily_call_entry_func lily_farm_call_table[] = { \
    NULL, \
    lily_farm_var_carrot_count, \
};
#endif
