#ifndef LILY_BACKBONE_BINDINGS_H
#define LILY_BACKBONE_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_BACKBONE_EXPORT __declspec(dllexport)
#else
#define LILY_BACKBONE_EXPORT
#endif

#define GET_Interpreter__import_hook(c_) \
lily_con_get(c_, 0)
#define SET_Interpreter__import_hook(c_, v_) \
lily_con_set(c_, 0, v_)
#define SETFS_Interpreter__import_hook(state, c_) \
lily_con_set_from_stack(state, c_, 0)
#define GET_Interpreter__raw(c_) \
lily_con_get(c_, 1)
#define SET_Interpreter__raw(c_, v_) \
lily_con_set(c_, 1, v_)
#define SETFS_Interpreter__raw(state, c_) \
lily_con_set_from_stack(state, c_, 1)
#define ID_Interpreter(s_) \
lily_cid_at(s_, 0)
#define SUPER_Interpreter(s_) \
lily_push_super(s_, ID_Interpreter(s_), 2)

#define ARG_RawInterpreter(s_, i_) \
(lily_backbone_RawInterpreter *)lily_arg_generic(s_, i_)
#define AS_RawInterpreter(v_) \
(lily_backbone_RawInterpreter *)lily_as_generic(v_)
#define ID_RawInterpreter(s_) \
lily_cid_at(s_, 1)
#define INIT_RawInterpreter(s_) \
(lily_backbone_RawInterpreter *)lily_push_foreign(s_, ID_RawInterpreter(s_), (lily_destroy_func)lily_backbone_destroy_RawInterpreter, sizeof(lily_backbone_RawInterpreter))

#define GET_TestCaseBase__fail_count(c_) \
lily_con_get(c_, 0)
#define SET_TestCaseBase__fail_count(c_, v_) \
lily_con_set(c_, 0, v_)
#define SETFS_TestCaseBase__fail_count(state, c_) \
lily_con_set_from_stack(state, c_, 0)
#define GET_TestCaseBase__pass_count(c_) \
lily_con_get(c_, 1)
#define SET_TestCaseBase__pass_count(c_, v_) \
lily_con_set(c_, 1, v_)
#define SETFS_TestCaseBase__pass_count(state, c_) \
lily_con_set_from_stack(state, c_, 1)
#define GET_TestCaseBase__skip_count(c_) \
lily_con_get(c_, 2)
#define SET_TestCaseBase__skip_count(c_, v_) \
lily_con_set(c_, 2, v_)
#define SETFS_TestCaseBase__skip_count(state, c_) \
lily_con_set_from_stack(state, c_, 2)
#define ID_TestCaseBase(s_) \
lily_cid_at(s_, 2)
#define SUPER_TestCaseBase(s_) \
lily_push_super(s_, ID_TestCaseBase(s_), 3)

LILY_BACKBONE_EXPORT
const char *lily_backbone_info_table[] = {
    "\3Interpreter\0RawInterpreter\0TestCaseBase\0"
    ,"N\34Interpreter\0"
    ,"m\0<new>\0: Interpreter"
    ,"m\0config_set_extra_info\0(Interpreter,Boolean): Interpreter"
    ,"m\0error\0(Interpreter): String"
    ,"m\0error_message\0(Interpreter): String"
    ,"m\0exit_code\0(Interpreter): Byte"
    ,"m\0has_exited\0(Interpreter): Boolean"
    ,"m\0import_current_root_dir\0(Interpreter): String"
    ,"m\0import_file\0(Interpreter,String): Boolean"
    ,"m\0import_hook_reset\0(Interpreter)"
    ,"m\0import_hook_set\0(Interpreter,Function(Interpreter,String))"
    ,"m\0import_library\0(Interpreter,String): Boolean"
    ,"m\0import_string\0(Interpreter,String,String): Boolean"
    ,"m\0import_use_local_dir\0(Interpreter,String)"
    ,"m\0import_use_package_dir\0(Interpreter,String)"
    ,"m\0new_sandboxed\0: Interpreter"
    ,"m\0open_math_library\0(Interpreter)"
    ,"m\0parse_expr\0(Interpreter,String,String): Option[String]"
    ,"m\0parse_file\0(Interpreter,String): Boolean"
    ,"m\0parse_manifest_file\0(Interpreter,String): Boolean"
    ,"m\0parse_manifest_string\0(Interpreter,String,String): Boolean"
    ,"m\0parse_string\0(Interpreter,String,String): Boolean"
    ,"m\0render_file\0(Interpreter,String): Option[String]"
    ,"m\0render_string\0(Interpreter,String,String): Option[String]"
    ,"m\0set_hook\0(Interpreter,Function(Interpreter,String))"
    ,"m\0validate_file\0(Interpreter,String): Boolean"
    ,"m\0validate_string\0(Interpreter,String,String): Boolean"
    ,"1\0import_hook\0Function(Interpreter,String)"
    ,"1\0raw\0RawInterpreter"
    ,"C\0RawInterpreter\0"
    ,"N\5TestCaseBase\0"
    ,"m\0<new>\0: TestCaseBase"
    ,"m\0run_tests\0(TestCaseBase)"
    ,"3\0fail_count\0Integer"
    ,"3\0pass_count\0Integer"
    ,"3\0skip_count\0Integer"
    ,"Z"
};
#define LILY_DECLARE_BACKBONE_CALL_TABLE \
LILY_BACKBONE_EXPORT \
lily_call_entry_func lily_backbone_call_table[] = { \
    NULL, \
    NULL, \
    lily_backbone_new_Interpreter, \
    lily_backbone_Interpreter_config_set_extra_info, \
    lily_backbone_Interpreter_error, \
    lily_backbone_Interpreter_error_message, \
    lily_backbone_Interpreter_exit_code, \
    lily_backbone_Interpreter_has_exited, \
    lily_backbone_Interpreter_import_current_root_dir, \
    lily_backbone_Interpreter_import_file, \
    lily_backbone_Interpreter_import_hook_reset, \
    lily_backbone_Interpreter_import_hook_set, \
    lily_backbone_Interpreter_import_library, \
    lily_backbone_Interpreter_import_string, \
    lily_backbone_Interpreter_import_use_local_dir, \
    lily_backbone_Interpreter_import_use_package_dir, \
    lily_backbone_Interpreter_new_sandboxed, \
    lily_backbone_Interpreter_open_math_library, \
    lily_backbone_Interpreter_parse_expr, \
    lily_backbone_Interpreter_parse_file, \
    lily_backbone_Interpreter_parse_manifest_file, \
    lily_backbone_Interpreter_parse_manifest_string, \
    lily_backbone_Interpreter_parse_string, \
    lily_backbone_Interpreter_render_file, \
    lily_backbone_Interpreter_render_string, \
    lily_backbone_Interpreter_set_hook, \
    lily_backbone_Interpreter_validate_file, \
    lily_backbone_Interpreter_validate_string, \
    NULL, \
    NULL, \
    NULL, \
    NULL, \
    lily_backbone_new_TestCaseBase, \
    lily_backbone_TestCaseBase_run_tests, \
    NULL, \
    NULL, \
    NULL, \
};
#endif
