#ifndef LILY_VIRT_BINDINGS_H
#define LILY_VIRT_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_VIRT_EXPORT __declspec(dllexport)
#else
#define LILY_VIRT_EXPORT
#endif

#define GET_virt_VOne__x(c_) \
lily_con_get(c_, 0)
#define SET_virt_VOne__x(c_, v_) \
lily_con_set(c_, 0, v_)
#define SETFS_virt_VOne__x(state, c_) \
lily_con_set_from_stack(state, c_, 0)
#define ID_virt_VOne(s_) \
lily_cid_at(s_, 0)
#define SUPER_virt_VOne(s_) \
lily_push_super(s_, ID_virt_VOne(s_), 1)

#define GET_virt_VThree__y(c_) \
lily_con_get(c_, 1)
#define SET_virt_VThree__y(c_, v_) \
lily_con_set(c_, 1, v_)
#define SETFS_virt_VThree__y(state, c_) \
lily_con_set_from_stack(state, c_, 1)
#define ID_virt_VThree(s_) \
lily_cid_at(s_, 1)
#define SUPER_virt_VThree(s_) \
lily_push_super(s_, ID_virt_VThree(s_), 2)

#define ID_virt_VTwo(s_) \
lily_cid_at(s_, 2)
#define SUPER_virt_VTwo(s_) \
lily_push_super(s_, ID_virt_VTwo(s_), 1)

LILY_VIRT_EXPORT
const char *lily_virt_info_table[] = {
    "\3VOne\0VThree\0VTwo\0"
    ,"N\5VOne\0"
    ,"m\0<new>\0: VOne"
    ,"m\0add_to_var\0(VOne,Integer): Integer"
    ,"m\0f\0(VOne)"
    ,"3\0x\0Integer"
    ,"t\0 1 1 v0:1"
    ,"N\5VThree\0< VTwo"
    ,"m\0<new>\0: VThree"
    ,"m\0add_to_var\0(VThree,Integer): Integer"
    ,"m\0get_name\0(VThree): String"
    ,"3\0y\0Integer"
    ,"t\0 2 2 v0:1v1:2"
    ,"N\4VTwo\0< VOne"
    ,"m\0<new>\0: VTwo"
    ,"m\0get_name\0(VTwo): String"
    ,"m\0h\0(VTwo)"
    ,"t\0i2 1 f1:1"
    ,"Z"
};
#define LILY_DECLARE_VIRT_CALL_TABLE \
LILY_VIRT_EXPORT \
lily_call_entry_func lily_virt_call_table[] = { \
    NULL, \
    NULL, \
    lily_virt_new_VOne, \
    lily_virt_VOne_add_to_var, \
    lily_virt_VOne_f, \
    NULL, \
    NULL, \
    NULL, \
    lily_virt_new_VThree, \
    lily_virt_VThree_add_to_var, \
    lily_virt_VThree_get_name, \
    NULL, \
    NULL, \
    NULL, \
    lily_virt_new_VTwo, \
    NULL, \
    lily_virt_VTwo_h, \
    NULL, \
};
#endif
