#ifndef LILY_COOL_BINDINGS_H
#define LILY_COOL_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_COOL_EXPORT __declspec(dllexport)
#else
#define LILY_COOL_EXPORT
#endif

#define cool_Color_Blue_VALUE 0
#define cool_Color_Green_VALUE 1
#define cool_Color_Purple_VALUE 2

LILY_COOL_EXPORT
const char *lily_cool_info_table[] = {
    "\1Color\0"
    ,"E\3Color\0< Integer"
    ,"V\0Blue\0=0"
    ,"V\0Green\0=1"
    ,"V\0Purple\0=2"
    ,"Z"
};
#define LILY_DECLARE_COOL_CALL_TABLE \
LILY_COOL_EXPORT \
lily_call_entry_func lily_cool_call_table[] = { \
    NULL, \
    NULL, \
    NULL, \
    NULL, \
    NULL, \
};
#endif
