/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

const char *lily_sys_dynaload_table[] = {
    "\0\0"
    ,"R\0argv\0List[String]"
    ,"F\0getenv\0(String):Option[String]"
    ,"Z"
};

void *lily_sys_loader(lily_state *s, int id)
{
    switch (id) {
        case 1: load_var_argv(s); return NULL;
        case 2: return lily_sys__getenv;
        default: return NULL;
    }
}

#define register_sys(p) lily_register_package(p, "sys", lily_sys_dynaload_table, lily_sys_loader);
