/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

const char *lily_random_dynaload_table[] = {
    "\1Random\0"
    ,"C\2Random"
    ,"m\0<new>\0(*Integer):Random"
    ,"m\0between\0(Random,Integer,Integer):Integer"
    ,"Z"
};

void *lily_random_loader(lily_options *o, uint16_t *c, int id)
{
    switch (id) {
        case 2: return lily_random_Random_new;
        case 3: return lily_random_Random_between;
        default: return NULL;
    }
}

#define register_random(p) lily_register_package(p, "random", lily_random_dynaload_table, lily_random_loader);
