/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

const char *lily_time_dynaload_table[] = {
    "\1Time\0"
    ,"C\4Time"
    ,"m\0clock\0:Double"
    ,"m\0now\0:Time"
    ,"m\0to_s\0(Time):String"
    ,"m\0since_epoch\0(Time):Integer"
    ,"Z"
};

void *lily_time_loader(lily_state *s, int id)
{
    switch (id) {
        case 2: return lily_time_Time_clock;
        case 3: return lily_time_Time_now;
        case 4: return lily_time_Time_to_s;
        case 5: return lily_time_Time_since_epoch;
        default: return NULL;
    }
}

#define register_time(p) lily_register_package(p, "time", lily_time_dynaload_table, lily_time_loader);
