/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

#define ARG_Random(state, index) \
(lily_random_Random *)lily_arg_generic(s, index)

#define ID_Random(state) lily_cid_at(state, 0)

#define INIT_Random(state) \
(lily_random_Random *)lily_new_foreign(state, ID_Random(s), (lily_destroy_func)destroy_Random, sizeof(lily_random_Random *))

