/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

#define ARG_Random(state, index) \
(lily_random_Random *)lily_arg_generic(s, index)

#define ID_Random(state) lily_cid_at(state, 0)

#define INIT_Random(state, target) \
target = lily_malloc(sizeof(lily_random_Random)); \
target->refcount = 0; \
target->destroy_func = (lily_destroy_func)destroy_Random;
