/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

#define ARG_Time(state, index) \
(lily_time_Time *)lily_arg_generic(s, index)

#define ID_Time(state) lily_cid_at(state, 0)

#define INIT_Time(state) \
(lily_time_Time *)lily_new_foreign(state, ID_Time(s), (lily_destroy_func)destroy_Time, sizeof(lily_time_Time *))

