/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

#define ARG_Time(state, index) \
(lily_time_Time *)lily_arg_generic(s, index)

#define ID_Time(state) lily_cid_at(state, 0)

#define INIT_Time(state, target) \
target = lily_malloc(sizeof(lily_time_Time)); \
target->refcount = 0; \
target->destroy_func = (lily_destroy_func)destroy_Time;
