/* Contents autogenerated by dyna_tools.py */
#include "lily_api_dyna.h"

#define ASSERTIONERROR_OFFSET      8
#define BOOLEAN_OFFSET             9
#define BYTE_OFFSET                12
#define BYTESTRING_OFFSET          14
#define DIVISIONBYZEROERROR_OFFSET 19
#define DOUBLE_OFFSET              21
#define DYNAMIC_OFFSET             23
#define EXCEPTION_OFFSET           25
#define FILE_OFFSET                29
#define FUNCTION_OFFSET            37
#define HASH_OFFSET                39
#define INDEXERROR_OFFSET          51
#define INTEGER_OFFSET             53
#define IOERROR_OFFSET             58
#define KEYERROR_OFFSET            60
#define LIST_OFFSET                62
#define OPTION_OFFSET              81
#define RESULT_OFFSET              94
#define RUNTIMEERROR_OFFSET        101
#define STRING_OFFSET              103
#define TUPLE_OFFSET               124
#define VALUEERROR_OFFSET          127
