#ifndef LILY_FS_BINDINGS_H
#define LILY_FS_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_FS_EXPORT __declspec(dllexport)
#else
#define LILY_FS_EXPORT
#endif

LILY_FS_EXPORT
const char *lily_fs_info_table[] = {
    "\0\0"
    ,"F\0change_dir\0(String)"
    ,"F\0create_dir\0(String,*Integer)"
    ,"F\0current_dir\0: String"
    ,"F\0remove_dir\0(String)"
    ,"Z"
};
#define LILY_DECLARE_FS_CALL_TABLE \
LILY_FS_EXPORT \
lily_call_entry_func lily_fs_call_table[] = { \
    NULL, \
    lily_fs__change_dir, \
    lily_fs__create_dir, \
    lily_fs__current_dir, \
    lily_fs__remove_dir, \
};
#endif
