#include "lily.h"
#include "lily_parser.h"
#include "lily_vm.h"

/* This file is automatically generated by scripts/prelude.lily. */

extern void lily_predefined_module_register(lily_parse_state *parser,
        const char *name, const char **info_table,
        lily_call_entry_func *call_table);

extern const char *lily_prelude_info_table[];
extern const char *lily_coroutine_info_table[];
extern const char *lily_fs_info_table[];
extern const char *lily_introspect_info_table[];
extern const char *lily_math_info_table[];
extern const char *lily_random_info_table[];
extern const char *lily_subprocess_info_table[];
extern const char *lily_sys_info_table[];
extern const char *lily_time_info_table[];

extern lily_call_entry_func lily_prelude_call_table[];
extern lily_call_entry_func lily_coroutine_call_table[];
extern lily_call_entry_func lily_fs_call_table[];
extern lily_call_entry_func lily_introspect_call_table[];
extern lily_call_entry_func lily_math_call_table[];
extern lily_call_entry_func lily_random_call_table[];
extern lily_call_entry_func lily_subprocess_call_table[];
extern lily_call_entry_func lily_sys_call_table[];
extern lily_call_entry_func lily_time_call_table[];

void lily_open_prelude_library(lily_parse_state *parser) {
    lily_predefined_module_register(parser, "prelude", lily_prelude_info_table, lily_prelude_call_table);
}

void lily_open_coroutine_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "coroutine", lily_coroutine_info_table, lily_coroutine_call_table);
}

void lily_open_fs_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "fs", lily_fs_info_table, lily_fs_call_table);
}

void lily_open_introspect_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "introspect", lily_introspect_info_table, lily_introspect_call_table);
}

void lily_open_math_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "math", lily_math_info_table, lily_math_call_table);
}

void lily_open_random_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "random", lily_random_info_table, lily_random_call_table);
}

void lily_open_subprocess_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "subprocess", lily_subprocess_info_table, lily_subprocess_call_table);
}

void lily_open_sys_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "sys", lily_sys_info_table, lily_sys_call_table);
}

void lily_open_time_library(lily_state *s) {
    lily_predefined_module_register(s->gs->parser, "time", lily_time_info_table, lily_time_call_table);
}

void lily_open_all_libraries(lily_state *s)
{
    lily_parse_state *parser = s->gs->parser;

    lily_predefined_module_register(parser, "coroutine", lily_coroutine_info_table, lily_coroutine_call_table);
    lily_predefined_module_register(parser, "fs", lily_fs_info_table, lily_fs_call_table);
    lily_predefined_module_register(parser, "introspect", lily_introspect_info_table, lily_introspect_call_table);
    lily_predefined_module_register(parser, "math", lily_math_info_table, lily_math_call_table);
    lily_predefined_module_register(parser, "random", lily_random_info_table, lily_random_call_table);
    lily_predefined_module_register(parser, "subprocess", lily_subprocess_info_table, lily_subprocess_call_table);
    lily_predefined_module_register(parser, "sys", lily_sys_info_table, lily_sys_call_table);
    lily_predefined_module_register(parser, "time", lily_time_info_table, lily_time_call_table);
}
