#ifndef LILY_RANDOM_BINDINGS_H
#define LILY_RANDOM_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_RANDOM_EXPORT __declspec(dllexport)
#else
#define LILY_RANDOM_EXPORT
#endif

#define ARG_Random(s_, i_) \
(lily_random_Random *)lily_arg_generic(s_, i_)
#define AS_Random(v_) \
(lily_random_Random *)lily_as_generic(v_)
#define ID_Random(s_) \
lily_cid_at(s_, 0)
#define INIT_Random(s_) \
(lily_random_Random *)lily_push_foreign(s_, ID_Random(s_), (lily_destroy_func)lily_random_destroy_Random, sizeof(lily_random_Random))

LILY_RANDOM_EXPORT
const char *lily_random_info_table[] = {
    "\1Random\0"
    ,"C\2Random\0"
    ,"m\0<new>\0(*Integer): Random"
    ,"m\0between\0(Random,Integer,Integer): Integer"
    ,"Z"
};
#define LILY_DECLARE_RANDOM_CALL_TABLE \
LILY_RANDOM_EXPORT \
lily_call_entry_func lily_random_call_table[] = { \
    NULL, \
    NULL, \
    lily_random_new_Random, \
    lily_random_Random_between, \
};
#endif
