#ifndef LILY_SUBPROCESS_BINDINGS_H
#define LILY_SUBPROCESS_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_SUBPROCESS_EXPORT __declspec(dllexport)
#else
#define LILY_SUBPROCESS_EXPORT
#endif

LILY_SUBPROCESS_EXPORT
const char *lily_subprocess_info_table[] = {
    "\0\0"
    ,"F\0popen\0(String,*String): File"
    ,"Z"
};
#define LILY_DECLARE_SUBPROCESS_CALL_TABLE \
LILY_SUBPROCESS_EXPORT \
lily_call_entry_func lily_subprocess_call_table[] = { \
    NULL, \
    lily_subprocess__popen, \
};
#endif
