#ifndef LILY_INTROSPECT_BINDINGS_H
#define LILY_INTROSPECT_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_INTROSPECT_EXPORT __declspec(dllexport)
#else
#define LILY_INTROSPECT_EXPORT
#endif

#define ARG_ClassEntry(s_, i_) \
(lily_introspect_ClassEntry *)lily_arg_generic(s_, i_)
#define AS_ClassEntry(v_) \
(lily_introspect_ClassEntry *)lily_as_generic(v_)
#define ID_ClassEntry(s_) \
lily_cid_at(s_, 0)
#define INIT_ClassEntry(s_) \
(lily_introspect_ClassEntry *)lily_push_foreign(s_, ID_ClassEntry(s_), (lily_destroy_func)destroy_ClassEntry, sizeof(lily_introspect_ClassEntry))

#define ARG_ConstantEntry(s_, i_) \
(lily_introspect_ConstantEntry *)lily_arg_generic(s_, i_)
#define AS_ConstantEntry(v_) \
(lily_introspect_ConstantEntry *)lily_as_generic(v_)
#define ID_ConstantEntry(s_) \
lily_cid_at(s_, 1)
#define INIT_ConstantEntry(s_) \
(lily_introspect_ConstantEntry *)lily_push_foreign(s_, ID_ConstantEntry(s_), (lily_destroy_func)destroy_ConstantEntry, sizeof(lily_introspect_ConstantEntry))

#define ARG_EnumEntry(s_, i_) \
(lily_introspect_EnumEntry *)lily_arg_generic(s_, i_)
#define AS_EnumEntry(v_) \
(lily_introspect_EnumEntry *)lily_as_generic(v_)
#define ID_EnumEntry(s_) \
lily_cid_at(s_, 2)
#define INIT_EnumEntry(s_) \
(lily_introspect_EnumEntry *)lily_push_foreign(s_, ID_EnumEntry(s_), (lily_destroy_func)destroy_EnumEntry, sizeof(lily_introspect_EnumEntry))

#define ARG_FunctionEntry(s_, i_) \
(lily_introspect_FunctionEntry *)lily_arg_generic(s_, i_)
#define AS_FunctionEntry(v_) \
(lily_introspect_FunctionEntry *)lily_as_generic(v_)
#define ID_FunctionEntry(s_) \
lily_cid_at(s_, 3)
#define INIT_FunctionEntry(s_) \
(lily_introspect_FunctionEntry *)lily_push_foreign(s_, ID_FunctionEntry(s_), (lily_destroy_func)destroy_FunctionEntry, sizeof(lily_introspect_FunctionEntry))

#define ARG_MethodEntry(s_, i_) \
(lily_introspect_MethodEntry *)lily_arg_generic(s_, i_)
#define AS_MethodEntry(v_) \
(lily_introspect_MethodEntry *)lily_as_generic(v_)
#define ID_MethodEntry(s_) \
lily_cid_at(s_, 4)
#define INIT_MethodEntry(s_) \
(lily_introspect_MethodEntry *)lily_push_foreign(s_, ID_MethodEntry(s_), (lily_destroy_func)destroy_MethodEntry, sizeof(lily_introspect_MethodEntry))

#define ARG_ModuleEntry(s_, i_) \
(lily_introspect_ModuleEntry *)lily_arg_generic(s_, i_)
#define AS_ModuleEntry(v_) \
(lily_introspect_ModuleEntry *)lily_as_generic(v_)
#define ID_ModuleEntry(s_) \
lily_cid_at(s_, 5)
#define INIT_ModuleEntry(s_) \
(lily_introspect_ModuleEntry *)lily_push_foreign(s_, ID_ModuleEntry(s_), (lily_destroy_func)destroy_ModuleEntry, sizeof(lily_introspect_ModuleEntry))

#define GET_ParameterEntry__keyword(c_) \
lily_con_get(c_, 0)
#define SET_ParameterEntry__keyword(c_, v_) \
lily_con_set(c_, 0, v_)
#define SETFS_ParameterEntry__keyword(state, c_) \
lily_con_set_from_stack(state, c_, 0)
#define GET_ParameterEntry__name(c_) \
lily_con_get(c_, 1)
#define SET_ParameterEntry__name(c_, v_) \
lily_con_set(c_, 1, v_)
#define SETFS_ParameterEntry__name(state, c_) \
lily_con_set_from_stack(state, c_, 1)
#define GET_ParameterEntry__type(c_) \
lily_con_get(c_, 2)
#define SET_ParameterEntry__type(c_, v_) \
lily_con_set(c_, 2, v_)
#define SETFS_ParameterEntry__type(state, c_) \
lily_con_set_from_stack(state, c_, 2)
#define ID_ParameterEntry(s_) \
lily_cid_at(s_, 6)
#define SUPER_ParameterEntry(s_) \
lily_push_super(s_, ID_ParameterEntry(s_), 3)

#define ARG_PropertyEntry(s_, i_) \
(lily_introspect_PropertyEntry *)lily_arg_generic(s_, i_)
#define AS_PropertyEntry(v_) \
(lily_introspect_PropertyEntry *)lily_as_generic(v_)
#define ID_PropertyEntry(s_) \
lily_cid_at(s_, 7)
#define INIT_PropertyEntry(s_) \
(lily_introspect_PropertyEntry *)lily_push_foreign(s_, ID_PropertyEntry(s_), (lily_destroy_func)destroy_PropertyEntry, sizeof(lily_introspect_PropertyEntry))

#define ARG_TypeEntry(s_, i_) \
(lily_introspect_TypeEntry *)lily_arg_generic(s_, i_)
#define AS_TypeEntry(v_) \
(lily_introspect_TypeEntry *)lily_as_generic(v_)
#define ID_TypeEntry(s_) \
lily_cid_at(s_, 8)
#define INIT_TypeEntry(s_) \
(lily_introspect_TypeEntry *)lily_push_foreign(s_, ID_TypeEntry(s_), (lily_destroy_func)destroy_TypeEntry, sizeof(lily_introspect_TypeEntry))

#define ARG_VarEntry(s_, i_) \
(lily_introspect_VarEntry *)lily_arg_generic(s_, i_)
#define AS_VarEntry(v_) \
(lily_introspect_VarEntry *)lily_as_generic(v_)
#define ID_VarEntry(s_) \
lily_cid_at(s_, 9)
#define INIT_VarEntry(s_) \
(lily_introspect_VarEntry *)lily_push_foreign(s_, ID_VarEntry(s_), (lily_destroy_func)destroy_VarEntry, sizeof(lily_introspect_VarEntry))

#define ARG_VariantEntry(s_, i_) \
(lily_introspect_VariantEntry *)lily_arg_generic(s_, i_)
#define AS_VariantEntry(v_) \
(lily_introspect_VariantEntry *)lily_as_generic(v_)
#define ID_VariantEntry(s_) \
lily_cid_at(s_, 10)
#define INIT_VariantEntry(s_) \
(lily_introspect_VariantEntry *)lily_push_foreign(s_, ID_VariantEntry(s_), (lily_destroy_func)destroy_VariantEntry, sizeof(lily_introspect_VariantEntry))

LILY_INTROSPECT_EXPORT
const char *lily_introspect_info_table[] = {
    "\013ClassEntry\0ConstantEntry\0EnumEntry\0FunctionEntry\0MethodEntry\0ModuleEntry\0ParameterEntry\0PropertyEntry\0TypeEntry\0VarEntry\0VariantEntry\0"
    ,"C\011ClassEntry\0"
    ,"m\0doc\0(ClassEntry): String"
    ,"m\0generics\0(ClassEntry): List[TypeEntry]"
    ,"m\0id\0(ClassEntry): Integer"
    ,"m\0is_foreign\0(ClassEntry): Boolean"
    ,"m\0is_native\0(ClassEntry): Boolean"
    ,"m\0methods\0(ClassEntry): List[MethodEntry]"
    ,"m\0name\0(ClassEntry): String"
    ,"m\0parent\0(ClassEntry): Option[ClassEntry]"
    ,"m\0properties\0(ClassEntry): List[PropertyEntry]"
    ,"C\03ConstantEntry\0"
    ,"m\0line_number\0(ConstantEntry): Integer"
    ,"m\0name\0(ConstantEntry): String"
    ,"m\0type\0(ConstantEntry): TypeEntry"
    ,"C\010EnumEntry\0"
    ,"m\0doc\0(EnumEntry): String"
    ,"m\0generics\0(EnumEntry): List[TypeEntry]"
    ,"m\0id\0(EnumEntry): Integer"
    ,"m\0is_flat\0(EnumEntry): Boolean"
    ,"m\0is_scoped\0(EnumEntry): Boolean"
    ,"m\0methods\0(EnumEntry): List[MethodEntry]"
    ,"m\0name\0(EnumEntry): String"
    ,"m\0variants\0(EnumEntry): List[VariantEntry]"
    ,"C\07FunctionEntry\0"
    ,"m\0doc\0(FunctionEntry): String"
    ,"m\0generics\0(FunctionEntry): List[TypeEntry]"
    ,"m\0line_number\0(FunctionEntry): Integer"
    ,"m\0name\0(FunctionEntry): String"
    ,"m\0parameters\0(FunctionEntry): List[ParameterEntry]"
    ,"m\0result_type\0(FunctionEntry): TypeEntry"
    ,"m\0type\0(FunctionEntry): TypeEntry"
    ,"C\013MethodEntry\0"
    ,"m\0doc\0(MethodEntry): String"
    ,"m\0function_name\0(MethodEntry): String"
    ,"m\0generics\0(MethodEntry): List[TypeEntry]"
    ,"m\0is_private\0(MethodEntry): Boolean"
    ,"m\0is_protected\0(MethodEntry): Boolean"
    ,"m\0is_public\0(MethodEntry): Boolean"
    ,"m\0is_static\0(MethodEntry): Boolean"
    ,"m\0line_number\0(MethodEntry): Integer"
    ,"m\0parameters\0(MethodEntry): List[ParameterEntry]"
    ,"m\0result_type\0(MethodEntry): TypeEntry"
    ,"m\0type\0(MethodEntry): TypeEntry"
    ,"C\020ModuleEntry\0"
    ,"m\0boxed_classes\0(ModuleEntry): List[ClassEntry]"
    ,"m\0boxed_constants\0(ModuleEntry): List[ConstantEntry]"
    ,"m\0boxed_enums\0(ModuleEntry): List[EnumEntry]"
    ,"m\0boxed_functions\0(ModuleEntry): List[FunctionEntry]"
    ,"m\0boxed_variants\0(ModuleEntry): List[VariantEntry]"
    ,"m\0boxed_vars\0(ModuleEntry): List[VarEntry]"
    ,"m\0classes\0(ModuleEntry): List[ClassEntry]"
    ,"m\0constants\0(ModuleEntry): List[ConstantEntry]"
    ,"m\0dirname\0(ModuleEntry): String"
    ,"m\0doc\0(ModuleEntry): String"
    ,"m\0enums\0(ModuleEntry): List[EnumEntry]"
    ,"m\0functions\0(ModuleEntry): List[FunctionEntry]"
    ,"m\0modules_used\0(ModuleEntry): List[ModuleEntry]"
    ,"m\0name\0(ModuleEntry): String"
    ,"m\0path\0(ModuleEntry): String"
    ,"m\0vars\0(ModuleEntry): List[VarEntry]"
    ,"N\04ParameterEntry\0"
    ,"m\0<new>\0(String,String,TypeEntry): ParameterEntry"
    ,"3\0keyword\0String"
    ,"3\0name\0String"
    ,"3\0type\0TypeEntry"
    ,"C\06PropertyEntry\0"
    ,"m\0doc\0(PropertyEntry): String"
    ,"m\0is_private\0(PropertyEntry): Boolean"
    ,"m\0is_protected\0(PropertyEntry): Boolean"
    ,"m\0is_public\0(PropertyEntry): Boolean"
    ,"m\0name\0(PropertyEntry): String"
    ,"m\0type\0(PropertyEntry): TypeEntry"
    ,"C\05TypeEntry\0"
    ,"m\0as_string\0(TypeEntry): String"
    ,"m\0class_id\0(TypeEntry): Integer"
    ,"m\0class_name\0(TypeEntry): String"
    ,"m\0inner_types\0(TypeEntry): List[TypeEntry]"
    ,"m\0is_vararg_function\0(TypeEntry): Boolean"
    ,"C\04VarEntry\0"
    ,"m\0doc\0(VarEntry): String"
    ,"m\0line_number\0(VarEntry): Integer"
    ,"m\0name\0(VarEntry): String"
    ,"m\0type\0(VarEntry): TypeEntry"
    ,"C\07VariantEntry\0"
    ,"m\0enum_id\0(VariantEntry): Integer"
    ,"m\0enum_name\0(VariantEntry): String"
    ,"m\0is_empty\0(VariantEntry): Boolean"
    ,"m\0is_scoped\0(VariantEntry): Boolean"
    ,"m\0name\0(VariantEntry): String"
    ,"m\0parameters\0(VariantEntry): List[ParameterEntry]"
    ,"m\0type\0(VariantEntry): TypeEntry"
    ,"F\0main_module\0: ModuleEntry"
    ,"F\0module_list\0: List[ModuleEntry]"
    ,"Z"
};
#define LILY_DECLARE_INTROSPECT_CALL_TABLE \
LILY_INTROSPECT_EXPORT \
lily_call_entry_func lily_introspect_call_table[] = { \
    NULL, \
    NULL, \
    lily_introspect_ClassEntry_doc, \
    lily_introspect_ClassEntry_generics, \
    lily_introspect_ClassEntry_id, \
    lily_introspect_ClassEntry_is_foreign, \
    lily_introspect_ClassEntry_is_native, \
    lily_introspect_ClassEntry_methods, \
    lily_introspect_ClassEntry_name, \
    lily_introspect_ClassEntry_parent, \
    lily_introspect_ClassEntry_properties, \
    NULL, \
    lily_introspect_ConstantEntry_line_number, \
    lily_introspect_ConstantEntry_name, \
    lily_introspect_ConstantEntry_type, \
    NULL, \
    lily_introspect_EnumEntry_doc, \
    lily_introspect_EnumEntry_generics, \
    lily_introspect_EnumEntry_id, \
    lily_introspect_EnumEntry_is_flat, \
    lily_introspect_EnumEntry_is_scoped, \
    lily_introspect_EnumEntry_methods, \
    lily_introspect_EnumEntry_name, \
    lily_introspect_EnumEntry_variants, \
    NULL, \
    lily_introspect_FunctionEntry_doc, \
    lily_introspect_FunctionEntry_generics, \
    lily_introspect_FunctionEntry_line_number, \
    lily_introspect_FunctionEntry_name, \
    lily_introspect_FunctionEntry_parameters, \
    lily_introspect_FunctionEntry_result_type, \
    lily_introspect_FunctionEntry_type, \
    NULL, \
    lily_introspect_MethodEntry_doc, \
    lily_introspect_MethodEntry_function_name, \
    lily_introspect_MethodEntry_generics, \
    lily_introspect_MethodEntry_is_private, \
    lily_introspect_MethodEntry_is_protected, \
    lily_introspect_MethodEntry_is_public, \
    lily_introspect_MethodEntry_is_static, \
    lily_introspect_MethodEntry_line_number, \
    lily_introspect_MethodEntry_parameters, \
    lily_introspect_MethodEntry_result_type, \
    lily_introspect_MethodEntry_type, \
    NULL, \
    lily_introspect_ModuleEntry_boxed_classes, \
    lily_introspect_ModuleEntry_boxed_constants, \
    lily_introspect_ModuleEntry_boxed_enums, \
    lily_introspect_ModuleEntry_boxed_functions, \
    lily_introspect_ModuleEntry_boxed_variants, \
    lily_introspect_ModuleEntry_boxed_vars, \
    lily_introspect_ModuleEntry_classes, \
    lily_introspect_ModuleEntry_constants, \
    lily_introspect_ModuleEntry_dirname, \
    lily_introspect_ModuleEntry_doc, \
    lily_introspect_ModuleEntry_enums, \
    lily_introspect_ModuleEntry_functions, \
    lily_introspect_ModuleEntry_modules_used, \
    lily_introspect_ModuleEntry_name, \
    lily_introspect_ModuleEntry_path, \
    lily_introspect_ModuleEntry_vars, \
    NULL, \
    lily_introspect_ParameterEntry_new, \
    NULL, \
    NULL, \
    NULL, \
    NULL, \
    lily_introspect_PropertyEntry_doc, \
    lily_introspect_PropertyEntry_is_private, \
    lily_introspect_PropertyEntry_is_protected, \
    lily_introspect_PropertyEntry_is_public, \
    lily_introspect_PropertyEntry_name, \
    lily_introspect_PropertyEntry_type, \
    NULL, \
    lily_introspect_TypeEntry_as_string, \
    lily_introspect_TypeEntry_class_id, \
    lily_introspect_TypeEntry_class_name, \
    lily_introspect_TypeEntry_inner_types, \
    lily_introspect_TypeEntry_is_vararg_function, \
    NULL, \
    lily_introspect_VarEntry_doc, \
    lily_introspect_VarEntry_line_number, \
    lily_introspect_VarEntry_name, \
    lily_introspect_VarEntry_type, \
    NULL, \
    lily_introspect_VariantEntry_enum_id, \
    lily_introspect_VariantEntry_enum_name, \
    lily_introspect_VariantEntry_is_empty, \
    lily_introspect_VariantEntry_is_scoped, \
    lily_introspect_VariantEntry_name, \
    lily_introspect_VariantEntry_parameters, \
    lily_introspect_VariantEntry_type, \
    lily_introspect__main_module, \
    lily_introspect__module_list, \
};
#endif
