#ifndef LILY_API_DYNA_H
# define LILY_API_DYNA_H

/* Only the files generated by dyna_tools.py should include this file. */

# ifndef LILY_STATE
#  define LILY_STATE
typedef struct lily_vm_state_ lily_state;
# endif

void lily_register_package(lily_state *, const char *, const char **, void *);
uint16_t lily_cid_at(lily_state *, int);

#endif
