#ifndef LILY_UTF8_BINDINGS_H
#define LILY_UTF8_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_UTF8_EXPORT __declspec(dllexport)
#else
#define LILY_UTF8_EXPORT
#endif

LILY_UTF8_EXPORT
const char *lily_utf8_info_table[] = {
    "\0\0"
    ,"F\0as_list\0(String): List[Integer]"
    ,"F\0compare\0(String,String): Integer"
    ,"F\0each_codepoint\0(String,Function(Integer))"
    ,"F\0encode\0(Integer): Option[String]"
    ,"F\0encode_list\0(List[Integer]): Option[String]"
    ,"F\0get\0(String,Integer): Integer"
    ,"F\0length\0(String): Integer"
    ,"F\0slice\0(String,*Integer,*Integer): String"
    ,"Z"
};
#define LILY_DECLARE_UTF8_CALL_TABLE \
LILY_UTF8_EXPORT \
lily_call_entry_func lily_utf8_call_table[] = { \
    NULL, \
    lily_utf8__as_list, \
    lily_utf8__compare, \
    lily_utf8__each_codepoint, \
    lily_utf8__encode, \
    lily_utf8__encode_list, \
    lily_utf8__get, \
    lily_utf8__length, \
    lily_utf8__slice, \
};
#endif
