#ifndef LILY_TIME_BINDINGS_H
#define LILY_TIME_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_TIME_EXPORT __declspec(dllexport)
#else
#define LILY_TIME_EXPORT
#endif

#define ARG_Time(s_, i_) \
(lily_time_Time *)lily_arg_generic(s_, i_)
#define AS_Time(v_) \
(lily_time_Time *)lily_as_generic(v_)
#define ID_Time(s_) \
lily_cid_at(s_, 0)
#define INIT_Time(s_) \
(lily_time_Time *)lily_push_foreign(s_, ID_Time(s_), (lily_destroy_func)lily_time_destroy_Time, sizeof(lily_time_Time))

LILY_TIME_EXPORT
const char *lily_time_info_table[] = {
    "\1Time\0"
    ,"C\4Time\0"
    ,"m\0clock\0: Double"
    ,"m\0now\0: Time"
    ,"m\0since_epoch\0(Time): Integer"
    ,"m\0to_s\0(Time): String"
    ,"Z"
};
#define LILY_DECLARE_TIME_CALL_TABLE \
LILY_TIME_EXPORT \
lily_call_entry_func lily_time_call_table[] = { \
    NULL, \
    NULL, \
    lily_time_Time_clock, \
    lily_time_Time_now, \
    lily_time_Time_since_epoch, \
    lily_time_Time_to_s, \
};
#endif
