#ifndef LILY_SYS_BINDINGS_H
#define LILY_SYS_BINDINGS_H
/* Generated by lily-bindgen, do not edit. */

const char *lily_sys_info_table[] = {
    "\0\0"
    ,"F\0getenv\0(String): Option[String]"
    ,"F\0recursion_limit\0: Integer"
    ,"F\0set_recursion_limit\0(Integer)"
    ,"R\0argv\0List[String]"
    ,"Z"
};
#define LILY_DECLARE_SYS_CALL_TABLE \
lily_call_entry_func lily_sys_call_table[] = { \
    NULL, \
    lily_sys__getenv, \
    lily_sys__recursion_limit, \
    lily_sys__set_recursion_limit, \
    lily_sys_var_argv, \
};
#endif
